// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXN7aNqNXuocrrmtTmeVDSwc1v0HVEZXM',
    appId: '1:65821237030:web:2c9402dc3a1ae31b272be7',
    messagingSenderId: '65821237030',
    projectId: 'fir-bookmark2',
    authDomain: 'fir-bookmark2.firebaseapp.com',
    storageBucket: 'fir-bookmark2.appspot.com',
    measurementId: 'G-E5QQS3ZMEV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNDjF73EchmG8SHF-dH6zMiv3Pl4xUiCY',
    appId: '1:65821237030:android:8010abaee48e584c272be7',
    messagingSenderId: '65821237030',
    projectId: 'fir-bookmark2',
    storageBucket: 'fir-bookmark2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8-WK2_ORcVyyUoaSyWJpQmTScTFwNtUA',
    appId: '1:65821237030:ios:625a4f404ba2c049272be7',
    messagingSenderId: '65821237030',
    projectId: 'fir-bookmark2',
    storageBucket: 'fir-bookmark2.appspot.com',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8-WK2_ORcVyyUoaSyWJpQmTScTFwNtUA',
    appId: '1:65821237030:ios:0e1ab4e3747c02da272be7',
    messagingSenderId: '65821237030',
    projectId: 'fir-bookmark2',
    storageBucket: 'fir-bookmark2.appspot.com',
    iosBundleId: 'com.example.instagram.RunnerTests',
  );
}
